"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "../styles/print.module.css";
import RootLayoutClient from "./RootLayoutClient";
import { ReduxProvider } from "../src/components/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   manifest: "/manifest.json",
//   title: "Rice Mill",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <RootLayoutClient>{children}</RootLayoutClient>
        </ReduxProvider>
      </body>
    </html>
  );
}
