import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "../styles/print.module.css"
import RootLayoutClient from "./RootLayoutClient";
import { PaymentProvider } from './paymentContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Rice Mill",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <PaymentProvider>
          <RootLayoutClient>
            {children}
          </RootLayoutClient>
        </PaymentProvider>
      </body>
    </html>
  );
}